apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx          # must match the labels in your Deployment
  ports:
  - protocol: TCP
    port: 80            # Service port exposed externally
    targetPort: 80      # Container port inside Pod
  type: LoadBalancer    # Exposes service externally
